[package]
name = "meow"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
irc = "0.15"
anyhow = "1.0"
crossterm = "0.26"
futures = "0.3"
futures-util = "0.3.31"
unicode-segmentation = "1.10"
