name: release ci/cd

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Install cross
        run: cargo install cross

      - name: Build with cross (x86_64)
        env:
          OPENSSL_STATIC: 1
        run: cross build --target x86_64-unknown-linux-gnu --release

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: meow-linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/meow

  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build x86_64
        run: cargo build --target x86_64-apple-darwin --release

      - name: Build aarch64
        run: cargo build --target aarch64-apple-darwin --release

      - name: Upload macOS x86_64
        uses: actions/upload-artifact@v4
        with:
          name: meow-macos-x86_64
          path: target/x86_64-apple-darwin/release/meow

      - name: Upload macOS aarch64
        uses: actions/upload-artifact@v4
        with:
          name: meow-macos-aarch64
          path: target/aarch64-apple-darwin/release/meow

  build-windows:
    name: Build Windows Binary
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --target x86_64-pc-windows-msvc --release

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: meow-windows-x86_64
          path: target/x86_64-pc-windows-msvc/release/meow.exe

  release:
    name: Publish GitHub Release
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/**/*
