name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        run: cargo install cross

      - name: Build x86_64-unknown-linux-gnu
        run: cross build --target x86_64-unknown-linux-gnu --release

      - name: Build aarch64-unknown-linux-gnu
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            target/x86_64-unknown-linux-gnu/release/meow
            target/aarch64-unknown-linux-gnu/release/meow

  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust targets
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build x86_64-apple-darwin
        run: cargo build --target x86_64-apple-darwin --release

      - name: Build aarch64-apple-darwin
        run: cargo build --target aarch64-apple-darwin --release

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: |
            target/x86_64-apple-darwin/release/meow
            target/aarch64-apple-darwin/release/meow

  build-windows:
    name: Build Windows Binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-msvc --release

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: target/x86_64-pc-windows-msvc/release/meow.exe

  release:
    name: Create GitHub Release
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Rename and flatten binaries
        run: |
          mkdir release
          cp artifacts/linux-binaries/* release/
          cp artifacts/macos-binaries/* release/
          cp artifacts/windows-binaries/* release/

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
